apiVersion: v1
kind: Service
metadata:
  labels:
    app: prod-chart-litmuschaos-server
  name: prod-chart-litmuschaos-server-service
  namespace: litmus-hub
spec:
  ports:
  - name: prod-chart-litmuschaos-server
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: prod-chart-litmuschaos-server
